-- CLBK setup for Radio PPI Dunia
-- Safe to run multiple times.

begin;

create table if not exists public.music_list (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text,
  image_url text,
  spotify_url text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.music_list add column if not exists title text;
alter table public.music_list add column if not exists artist text;
alter table public.music_list add column if not exists image_url text;
alter table public.music_list add column if not exists spotify_url text;
alter table public.music_list add column if not exists sort_order integer not null default 0;
alter table public.music_list add column if not exists is_active boolean not null default true;
alter table public.music_list add column if not exists created_at timestamptz not null default now();
alter table public.music_list add column if not exists updated_at timestamptz not null default now();

create index if not exists music_list_sort_order_idx on public.music_list(sort_order);
create index if not exists music_list_is_active_idx on public.music_list(is_active);

-- Keep only one item per ranking slot.
create unique index if not exists music_list_sort_order_unique_idx on public.music_list(sort_order);

-- Replace current CLBK top 10.
delete from public.music_list where sort_order between 1 and 10;

insert into public.music_list (title, artist, image_url, spotify_url, sort_order, is_active)
values
  ('Rindu Dalam Frekuensi', 'Aulia Ramadhan', 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?q=80&w=800&auto=format&fit=crop', 'https://open.spotify.com/', 1, true),
  ('Langit Pagi Jakarta', 'Nadya Prameswari', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=800&auto=format&fit=crop', 'https://open.spotify.com/', 2, true),
  ('Malam di Perantauan', 'SSK Elang', 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?q=80&w=800&auto=format&fit=crop', 'https://open.spotify.com/', 3, true),
  ('Satu Cinta Satu Nada', 'RPD Collective', 'https://images.unsplash.com/photo-1464375117522-1311dd6d0cd2?q=80&w=800&auto=format&fit=crop', 'https://open.spotify.com/', 4, true),
  ('Pulang Lewat Gelombang', 'Mikha Tanuwijaya', 'https://images.unsplash.com/photo-1501612780327-45045538702b?q=80&w=800&auto=format&fit=crop', 'https://open.spotify.com/', 5, true),
  ('Kota, Kopi, dan Kamu', 'Vira Kusuma', 'https://images.unsplash.com/photo-1494232410401-ad00d5433cfa?q=80&w=800&auto=format&fit=crop', 'https://open.spotify.com/', 6, true),
  ('Batas Waktu Bahagia', 'Fikri Hidayat', 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?q=80&w=800&auto=format&fit=crop', 'https://open.spotify.com/', 7, true),
  ('Arah Selatan', 'Dinda Mutiara', 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?q=80&w=800&auto=format&fit=crop', 'https://open.spotify.com/', 8, true),
  ('Siaran Tengah Malam', 'Yusuf Aksan', 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?q=80&w=800&auto=format&fit=crop', 'https://open.spotify.com/', 9, true),
  ('Cerita Pulang', 'Bima Pratama', 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?q=80&w=800&auto=format&fit=crop', 'https://open.spotify.com/', 10, true);

alter table public.music_list enable row level security;

drop policy if exists "music_list_public_read" on public.music_list;
create policy "music_list_public_read"
  on public.music_list
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "music_list_authenticated_write" on public.music_list;
create policy "music_list_authenticated_write"
  on public.music_list
  for all
  to authenticated
  using (true)
  with check (true);

commit;
